### ISSUE TITLE
Fails with FD error line 170 on macOS or BSD

### ISSUE THREAD

**Issue by paulhargreaves** [crypt1d/redi.sh#11]
Doesn't work at all on macOS, it appears to be using some hardcoded echoing to a file in /dev that doesn't exist.

```
$ echo "this is a variable" | ./redi.sh -s testvar -H server.local
./redi.sh: line 170: exec: {FD}: not found
$ ./redi.sh -g testvar -H server.local
./redi.sh: line 170: exec: {FD}: not found

$ uname -a
Darwin ProBook.local 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64
```

The line is this:
`exec {FD}<> /dev/tcp/"$REDIS_HOST"/"$REDIS_PORT"
`
macOS doesn't have a /dev/tcp. This isn't really a bash-only script, I assume it is a Linux only script?

Similarly, on a FreeBSD box;
```
$ ls /dev/tcp
ls: /dev/tcp: No such file or directory
$ 
```

**Comment by crypt1d** [comment]
/dev/tcp is a Bash built-in intercept, not a OS-specific pseudo-device. So it will not be visible on Linux either if u do `ls -l` on it.

Instead, you should make sure that your Bash is compiled with `--enable-net-redirections` option in order for this to work. This is by default on most/all Linux distros, but I'm not sure how it is on Mac/FreeBSD.

http://www.tldp.org/LDP/abs/html/devref1.html#DEVTCP

**Comment by crypt1d** [comment]
However, upon having a better look at your problem I see the issue is not with the intercept but with the `{FD}` file descriptor variable.

The script uses the `exec {FD}` function to assign the lowest available file descriptor to the TCP socket. This is also a 'bashism' that should be OS-agnostic, so I'm not sure why its not working on a Mac. I'll have to have a better look at it.

**Comment by crypt1d** [comment]
So I just checked this on my mac. Turns out that the default Bash version that comes with MacOS is quite old - 3.2. Most of the Linux distributions now-a-days run on Bash 4.2 at least.
You should install a newer bash version using brew or a similar package manager for MacOS. 
After that make sure that the script runs with `/usr/local/bin/bash` instead of `/bin/bash` and you are good to go.

**Comment by paulhargreaves** [comment]
Ah yes.

This might help:
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.

Amazing how up to date bash is on macOS (10.12...)

[https://jira.hpdd.intel.com/browse/LU-4030](https://jira.hpdd.intel.com/browse/LU-4030) has the same error message shown, where they say the  {FD}<> is a bash 4.0ism.

**Comment by paulhargreaves** [comment]
Like a good joke, timing is everything. Ok, will brew a newer version. Thanks!
